### ISSUE TITLE
board-group extension doesn't observe "for" and "not" constraints on transitions

### ISSUE THREAD

**Issue by Gabriele2** [ostreifel/Board-Group#10]
I'm using TFS 2017 update 1 on premises. In my custom process templates I configured many constraints on transitions like the following:

<TRANSITION from="Draft" to="New" for="[project]\User Stories Contributors" >

For details on transition constraints see https://docs.microsoft.com/en-us/vsts/work/customize/reference/transition-xml-element#attributes-and-elements

Please resolve this issue because Board Group is a very useful extension but I cannot use it in my production environment since it doesn't observe "for" and "not" transition constrains.

**Comment by ostreifel** [comment]
I can add limitations based on the current state but rules like for/not are not exposed to extensions and new apis would be required for those to be accounted for by the board group.

**Comment by Gabriele2** [comment]
Ok. What is the method you currently use to change workitem state from any state to any state? Could you please show me what is the part of source code in you invoke this method. I'd like to have this information because I'd like to suggest through uservoice the adding of methods for managing rules like for/not in api for extension.

**Comment by ostreifel** [comment]
All of the logic for changing the columns is all in 
https://github.com/ostreifel/Board-Group/blob/master/scripts/boardModel.ts
I have updated it to restrict to only allowed state transitions here but haven't gotten around to testing it.
https://github.com/ostreifel/Board-Group/blob/users/ottost/states/scripts/boardModel.ts

**Comment by ostreifel** [comment]
The logic for state based restrictions when moving columns is now live.
File an issue to [user voice](https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services) for the for/not rules to be exposed
