### ISSUE TITLE
Context menu options don't show the first time

### ISSUE THREAD

**Issue by deviruchi** [ostreifel/Board-Group#13]
After a page refresh, the context menu on the board card doesn't show and you have to click off and back on the item to make it show.
I've included a short video of the issue.
[bandicam 2018-02-23 14-58-36-858.zip](https://github.com/ostreifel/Board-Group/files/1752097/bandicam.2018-02-23.14-58-36-858.zip)

**Comment by ostreifel** [comment]
This a perf issue wherein the first load takes longer than the page will wait for the menu items. I can think of a few optimizations can be made here - will need to test to see if they are enough.

**Comment by ostreifel** [comment]
Updated to reduce load time on board and backlogs.
Extension version 2.5.45
