### ISSUE TITLE
Missing board group on Work Item form in TFS

### ISSUE THREAD

**Issue by MagnusTim** [ostreifel/Board-Group#14]
Hi,

Thanks for a really nice tool!

I installed the board Group tool in TFS 2017.3 but the board gropup is missing in the Work Item form.
Do you have any suggestions? DO I have to modify the form in any way?

/Magnus

**Comment by ostreifel** [comment]
[Yes](https://marketplace.visualstudio.com/items?itemName=ottostreifel.board-group#user-content-configuration-using-process-template) for each work item type add the extension and the group to /WITD/WORKITEMTYPE/FORM/WebLayout see the link for more details.

**Comment by MagnusTim** [comment]
Thanks for Quick response. I will try this.

/Magnus
