### ISSUE TITLE
Unable to add the extension

### ISSUE THREAD

**Issue by vinaysandela** [ostreifel/Board-Group#15]
I am trying to add the Board Group Version 2.5.48. I am using TFS 2017 Update 3.

When I click install - getting this

_Something's gone wrong
We've encountered an error while downloading the extension. Please try again later._

Can you please check and help me in installing. Thanks

**Comment by ostreifel** [comment]
https://marketplace.visualstudio.com/acquisition?itemName=ottostreifel.board-group


[ottostreifel.board-group-2.5.48.zip](https://github.com/ostreifel/Board-Group/files/1807751/ottostreifel.board-group-2.5.48.zip)

**Comment by vinaysandela** [comment]
I have tried that getting the atttached error.

[VSIXInstaller_c754b6e9-8d12-4017-941c-6c0fdf35fd8e.log](https://github.com/ostreifel/Board-Group/files/1807809/VSIXInstaller_c754b6e9-8d12-4017-941c-6c0fdf35fd8e.log)
