### ISSUE TITLE
Unable to add the extension

### ISSUE THREAD

**Issue by vinaysandela** [ostreifel/Board-Group#16]
I am trying to add the Board Group Version 2.5.48. I am using TFS 2017 Update 3. Looks like this extension would help me, but facing issues in installing. Please help

When I click install - getting this
_Something's gone wrong
We've encountered an error while downloading the extension. Please try again later._

I have also tried with a copy of the downloaded extension in a zip file
ottostreifel.board-group-2.5.48.zip

Got the attached error - 
[VSIXInstaller_c754b6e9-8d12-4017-941c-6c0fdf35fd8e.log](https://github.com/ostreifel/Board-Group/files/1808215/VSIXInstaller_c754b6e9-8d12-4017-941c-6c0fdf35fd8e.log)

**Comment by pkuma-msft** [comment]
HI @vinaysandela , it looks like you're trying to install the extension by double clicking on the .vsix file? Can you follow the steps outlined here and see if it works for you?
https://docs.microsoft.com/en-us/vsts/marketplace/get-tfs-extensions

Let us know if you still run into issues.

**Comment by vinaysandela** [comment]
Thanks!
I have downloaded and uploaded the extension and its working great.
