### ISSUE TITLE
Board Column value reverted to Active

### ISSUE THREAD

**Issue by Vertex-btb** [ostreifel/Board-Group#17]
In our project, we have ~8 custom board columns (neither of which is named "Active").  Recently we noticed that the 'Board Column' value displayed within the form for most of our work items had somehow been set to "Active."  Although the value displays as "Active", the records are displayed in the correct column when viewing the Board.  Yet, when viewing the records in the Backlog or Query results, "Active" is displayed.  This presents issue with Reporting and filtering. 

Since "Active" is not a board column, we're unable to see this value in the drop downs, and therefore do not believe this value was entered by a user.  Rather, we believe the Board-Group extension may have caused the data issue.  Due to this issue, the team had to manually reset all work item board column values back to the correct setting. 

Can you assist?

**Comment by ostreifel** [comment]
Are there multiple boards that the work item can fall under? One of the ways that this can happen is if the board column field is picking up the wrong board.

![image](https://user-images.githubusercontent.com/5203542/37545340-cb0405fc-2925-11e8-83d4-4d1449975910.png)

**Comment by Vertex-btb** [comment]
Otto, 

You're a genius!  We had multiple Teams configured, and one of the teams still had generic states ("Active", etc...).  Although none of the team member recall changing a value, the team often uses the TFS Office Integration plug-in, and most likely accidentally reset the values while processing a bulk edit of another field.

Thank you for the quick response.  We love using this extension. 

- Brendan

**Comment by Vertex-btb** [comment]
Closing the issue.
