### ISSUE TITLE
"No board found for current area path" unklar (unclear)

### ISSUE THREAD

**Issue by weird-dreams** [ostreifel/Board-Group#18]
We are getting this error on one WorkItem - most other haven't such error:
![image](https://user-images.githubusercontent.com/11518242/38925600-65a21e48-4300-11e8-985f-bdbd991e6df0.png)
What is the reason for this?
How are Boards connected with area paths?

**Comment by ostreifel** [comment]
Work items will show on a board if they are

- on the areapath associated with that team
- the right work item type for the board
- not cut

If any of those conditions are not met then that message will show.

**Comment by weird-dreams** [comment]
OK. Thank you! A new area path was missing.
What do you mean with  "not cut"?

**Comment by ostreifel** [comment]
Certain work item states do not have board column mappings and will not appear on the board when they are moved to those states. Often these states are called "Cut", "Removed" or something similar.

![image](https://user-images.githubusercontent.com/5203542/39006254-60d47d2c-43b7-11e8-9384-f43073879ea1.png)
