### ISSUE TITLE
Subareas not shown on correct team

### ISSUE THREAD

**Issue by MagnusTim** [ostreifel/Board-Group#19]
Hi Otto,
Thanks for a really nice tool!

We have a structure with hierarchical teams (teams in teams) and if we in the one of the sub teams have a subarea, a work item placed there does not show the correct team, it only shows the higher team area (do you understand what I mean).

![image](https://user-images.githubusercontent.com/20904922/40295068-4a879f88-5cd8-11e8-9115-59ec60a6e30e.png)

In the picture SRS is a sub team and Admin is a subarea that ends up in Team MH

![image](https://user-images.githubusercontent.com/20904922/40295123-832127c4-5cd8-11e8-9430-c30289afd0e9.png)

/Magnus

**Comment by ostreifel** [comment]
From the screen shot above it would seem that the reason for this is that neither srs or admin have explicit owners and so the extension is walking back up the tree - sees that 'Team Ah' and it children are owned by Team ah and uses that as the team assignment.

Now about changing assignments - areapath ownerships are cached by the extension for 1 day b/c of a limitation in the apis available makes retrieving that information slow. This refresh can be forced earlier than 1 day by either opening the board group with an area path it hasn't seen before or by manually calling the delete method on the url used to get the document using postman or equivalent.

**Comment by ostreifel** [comment]
Owner should appear here.
![image](https://user-images.githubusercontent.com/5203542/40403560-792df456-5e07-11e8-9291-9e3c1a611493.png)
To add an owner go to the project work settings for that team and add the area path

https://&lt;collection&gt;/&lt;proj&gt;/&lt;team&gt;/_admin/_work?_a=areas

**Comment by MagnusTim** [comment]
OK, thanks!
