### ISSUE TITLE
Borad extension missing from some users 

### ISSUE THREAD

**Issue by MagnusTim** [ostreifel/Board-Group#20]
Hi again,

We have Another rather strange problem. The board extenstion is missing for some users, not all when a work item is opened, not in the backlog. Also its just for one work item type (PBI)

Se definition here
[Product Backlog Item (1).txt](https://github.com/ostreifel/Board-Group/files/2022546/Product.Backlog.Item.1.txt)

And how it looks for not working users here.
![image](https://user-images.githubusercontent.com/20904922/40308380-626c43d2-5d06-11e8-91a0-2e598c8c4764.png)

Regards Magnus

**Comment by ostreifel** [comment]
In this case the group itself is collapsed
![image](https://user-images.githubusercontent.com/5203542/40339097-9fcfe52c-5d2d-11e8-9b97-98483b7d3ba0.png)

Sometimes the extension is loaded but not properly sized in this case you will need to click refresh on the work item form to get the render completed. I suspect this is the case in above.

**Comment by MagnusTim** [comment]
Thanks !
