### ISSUE TITLE
Work item templates can't set a starting board

### ISSUE THREAD

**Issue by brphelps** [ostreifel/Board-Group#21]
Title says it all -- Is this something that can be accomplished with an additional extension?

**Comment by ostreifel** [comment]
You actually can

set the areapath of the template to an areapath owned by the board - this means that the team associated with that board owns that areapath

**Comment by brphelps** [comment]
Can this be used to set lanes as well?

**Comment by ostreifel** [comment]
You would need to use the [rest api's](https://docs.microsoft.com/en-us/rest/api/vsts/wit/templates/create?view=vsts-rest-4.1) directly in an extension for that b/c the lane field for each board is not exposed in the field dropdowns.
