### ISSUE TITLE
npm install fails on gulp clean

### ISSUE THREAD

**Issue by pabrams** [ostreifel/Board-Group#26]
I'll submit a PR shortly...

> [11:55:22] Starting 'package'...
> [11:55:22] Starting 'clean'...
> [11:55:22] 'clean' errored after 16 ms
> [11:55:22] Error: File not found with singular glob: C:/Repos/Board-Group/dist (if this was purposeful, use `allowEmpty` option)
>     at Glob.<anonymous> (C:\Repos\Board-Group\node_modules\glob-stream\readable.js:84:17)
>     at Object.onceWrapper (events.js:315:30)
>     at emitOne (events.js:116:13)
>     at Glob.emit (events.js:211:7)
>     at Glob._finish (C:\Repos\Board-Group\node_modules\glob\glob.js:197:8)
>     at done (C:\Repos\Board-Group\node_modules\glob\glob.js:182:14)
>     at Glob._processSimple2 (C:\Repos\Board-Group\node_modules\glob\glob.js:688:12)
>     at C:\Repos\Board-Group\node_modules\glob\glob.js:676:10
>     at Glob._stat2 (C:\Repos\Board-Group\node_modules\glob\glob.js:772:12)
>     at lstatcb_ (C:\Repos\Board-Group\node_modules\glob\glob.js:764:12)
> [11:55:22] 'package' errored after 19 ms
> [11:55:22] 'default' errored after 21 ms

**Comment by ostreifel** [comment]
Thank you for fixing this.
