### ISSUE TITLE
New Feature Suggestion

### ISSUE THREAD

**Issue by jmconnell2000** [ostreifel/Board-Group#30]
I would be helpful if the card on the board would help us better identify stagnant work items. Perhaps we can have an Icon or a color on the card to indicate no change in progress to the next column in the last 24 hours.

Also might be helpful to see if card has been recycled directly from the item card as well.

**Comment by SteffanMcC** [comment]
https://docs.microsoft.com/en-us/azure/devops/boards/boards/customize-cards?view=azure-devops#define-style-rules-to-highlight-cards
