### ISSUE TITLE
Board Group Extension Appears Twice

### ISSUE THREAD

**Issue by SteffanMcC** [ostreifel/Board-Group#33]
**Describe the bug**
The board group extension is duplicated on a work item. The first extension shows the correct column, but the column position is stuck in "Loading position". Underneath is a second instance of the extension with the appropriate column and position. When you update the column, the extension corrects itself and shows the extension properly. 

In console, the team path is showing a 404. Also getting error 1660002, The collection does not exist. 

**Environment:**
 - Browser - Chrome and Safari 
 - Hosted (Azure Devops)

**Screenshots**
![image](https://user-images.githubusercontent.com/53578066/65512859-1766dd00-dea8-11e9-9dff-9455b54df50d.png)
![image](https://user-images.githubusercontent.com/53578066/65512965-4aa96c00-dea8-11e9-9483-72c3905a6e17.png)

**To Reproduce**
I can not completely confirm this, but it does not appear any organizational or environment change caused this. 

**Expected behavior**
The board group extension should only load once. 

**Additional context**
I have tried uninstalling and reinstalling the extension.

**Comment by ostreifel** [comment]
Just pushed a quick fix for the double render.

What is the stack trace for where the collection error is being thrown? Or the url that the extension is trying to hit?

Does this happen in all projects on the account?

**Comment by SteffanMcC** [comment]
We no longer get the duplicate render. Thanks for the quick fix. 

The url and error in the console is: 
![image](https://user-images.githubusercontent.com/53578066/65600257-d1744c80-df6d-11e9-8804-88b819f643e6.png)

I still get error 1660002 in my sandbox environment. In my actual organization, I still see a similar 404 in the console for all projects. Although the error is now: "TF1590005: Document with id preferred-team does not exist in collection User for ... a guid + team path". 

![image](https://user-images.githubusercontent.com/53578066/65602222-82301b00-df71-11e9-9f97-193b05af6b9f.png)

**Comment by ostreifel** [comment]
404 for preferred-team is expected behavior. Everything looks good now.
