### ISSUE TITLE
Any plans to expose this to Power Automate?

### ISSUE THREAD

**Issue by juliano-g-lopes** [ostreifel/Board-Group#45]
Hi folks,

I'm creating a set of automation tools based on my Devops boards that basically allows the devs to concentrate in work and in moving only tasks, purely. All the other types that are envolve in this scenario, like Epic, User Story and some custom types, I was able to automatize the job of moving them between States.

But, there's one board with some swimlanes: for this specific point, I need to, through Power Automate, be able to move a item between board columns and in the correct swimlane. But, unfortunately the Board Column is read only for default.

After some given context, then become the question: considering that everything listed in a type (like User story) is exposed to Power Automate, there is any plans to include any field that goes through this and allow to change the item between columns? I look at User Story fields exposed, but I wasn't able to find anything that allow me to change the column, just the regular ones.

Thanks and regards,

Juliano

**Comment by ostreifel** [comment]
This is only an extension. The link for requesting new features in Azure Boards is: 
https://developercommunity.visualstudio.com/spaces/21/visual-studio-team-services.html?type=idea
