### ISSUE TITLE
Ability to change the board column of a backlog item from the sprint board

### ISSUE THREAD

**Issue by dlongman** [ostreifel/Board-Group#5]
It would be really nice if it was possible to change the board column of a Product Backlog Item (PBI) directly from the sprint board. Currently the menu does not appear on the card menu when viewing the PBI on the sprint board.

Our workflow moves a PBI from Committed to Ready for Release rather than Done during a sprint so it would be nice to be able to do this directly on the Sprint board rather than having to go back to the main board to move the PBI.

**Comment by dlongman** [comment]
This sounds related to issue #1 but I do not need to be able to set the column for the tasks themselves, only the PBI. Here's an example

![example](https://user-images.githubusercontent.com/2796109/28316084-2c736be6-6bb9-11e7-884b-22786c42b6a0.png)

**Comment by ostreifel** [comment]
In the above example the board settings can be modified to include the state in the fields displayed on the task card so the extension would still be a fifth wheel in the experience.

**Comment by dlongman** [comment]
@ostreifel I'm not sure how adding the state to the fields displayed would help. We want to change the column on the Backlog board that the story is in directly from the sprint backlog board. This is not possible with native TFS behaviour. Adding the Board Column field to the card is no help because that is non-editable.

I think the value of the extension on the Sprint board is the same as having it on the Backlog list view.

**Comment by ostreifel** [comment]
Added it 2.4.48

**Comment by dlongman** [comment]
That's perfect thanks @ostreifel - that is exactly what I was after.

It would be much nicer if the Sprint board could be set to update automatically so the new board column is reflected in the UI immediately like the main boards but I appreciate that is a VSTS enhancement rather than with this extension :-)

Thanks for adding this.
